---

title: "The JS Foundation"
description: "The JS Foundation is a member supported non-profit trade association for web developers."
keywords: "JS, Foundation, open source, JavaScript, jQuery"

url: "https://js.foundation"
baseurl: ""

host: 0.0.0.0
port: 4000
safe: true
timezone: Europe/London

include:
  - _pages
  - .htacces
exclude:
  - CNAME
  - README.md
  - .git
  - Gemfile
  - Gemfile.lock

markdown: kramdown
highlighter: rouge
sass:
  style: :compressed

permalink: pretty

collections:
  projects:
  events:
  announcements:
    output: true
    permalink: "/announcements/:year/:month/:day/:title/"

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: "/:basename/"
      layout: "left"
  - scope:
      path: "_pages/index.md"
    values:
      permalink: "/index.html"
      layout: "home"
  - scope:
      path: "_pages/404.md"
    values:
      permalink: "/404.html"
      layout: "center"
  - scope:
      path: "_pages/projects.md"
    values:
      layout: "cards"
  - scope:
      path: "_pages/events.md"
    values:
      layout: "cards"
  - scope:
      path: "_pages/announcements.md"
    values:
      layout: "announcements"
  - scope:
      path: ""
      type: "announcements"
    values:
      layout: "announcement"
  - scope:
      path: "_pages/blog.md"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:categories/:year/:month/:day/:title/"
      layout: "post"

google_analytics_id: "UA-1076265-4"

twitter: the_jsf
github: JSFoundation
