---

port: 4000
host: 0.0.0.0
safe: false

### collections ###
collections:
  home:
    permalink: /
  conduct:
    permalink: /conduct/
  bylaws:
    permalink: /bylaws/
  license:
    permalink: /license/
  mission:
    permalink: /mission/
  trademark:
    permalink: /trademark/

### site serving configuration ###
exclude: [CNAME, README.md, .git]
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "The jQuery Foundation"
keywords:    "jQuery, Foundation, open source, JavaScript"
description: "The jQuery Foundation is a member supported non-profit trade association for web developers."
source_link: "https://github.com/jquery-foundation/jquery.org"
favicon:     ""
touch_icon:  ""
google_analytics_key: "UA-1076265-4" ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#333333'
  grey:      '#dddddd'
  white:     '#f8f8f8'
  blue-1:    '#0769ad'
  green:     '#3eb249'
  purple:    '#390f39'
  orange:    '#faa523'
  blue-2:    '#7acef4'
  red:       '#9a1b1e'

kramdown:
  auto_ids:  false
